import PDFDocument from "pdfkit";
import type { FinancialExportData } from "@/lib/export/aggregateFinancials";

function formatAmount(value: number): string {
  return `INR ${value.toFixed(2)}`;
}

function formatDateDDMMYYYY(value: string): string {
  if (!value) return "";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  const day = String(date.getUTCDate()).padStart(2, "0");
  const month = String(date.getUTCMonth() + 1).padStart(2, "0");
  const year = date.getUTCFullYear();
  return `${day}/${month}/${year}`;
}

function drawMetricCard(params: {
  doc: PDFKit.PDFDocument;
  x: number;
  y: number;
  width: number;
  height: number;
  label: string;
  value: number;
  color: string;
}) {
  const { doc, x, y, width, height, label, value, color } = params;
  doc.save();
  doc.roundedRect(x, y, width, height, 8).fill(color);
  doc.fillColor("#111827").font("Helvetica-Bold").fontSize(11).text(label, x + 12, y + 12, { width: width - 24 });
  doc
    .fillColor("#0F172A")
    .font("Helvetica-Bold")
    .fontSize(17)
    .text(formatAmount(value), x + 12, y + 36, { width: width - 24 });
  doc.restore();
}

function drawFooter(params: {
  doc: PDFKit.PDFDocument;
  page: number;
  totalPages: number;
  generatedAt: string;
}) {
  const { doc, page, totalPages, generatedAt } = params;
  const footerY = doc.page.height - 35;
  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor("#6B7280")
    .text(`Page ${page} of ${totalPages}`, 50, footerY, { align: "left" });
  doc
    .font("Helvetica")
    .fontSize(9)
    .fillColor("#6B7280")
    .text(`Generated by BizDhan on ${generatedAt}`, 50, footerY, { align: "right" });
}

export async function generatePDF(data: FinancialExportData): Promise<Buffer> {
  const doc = new PDFDocument({ margin: 50, size: "A4", bufferPages: true });
  const buffers: Buffer[] = [];
  doc.on("data", (b) => buffers.push(b));
  const pdfEnd = new Promise<Buffer>((resolve) => doc.on("end", () => resolve(Buffer.concat(buffers))));

  // Page 1 - cover + summary
  doc.font("Helvetica-Bold").fontSize(24).fillColor("#111827").text("BizDhan Financial Report", 50, 65);
  doc
    .font("Helvetica")
    .fontSize(14)
    .fillColor("#6B7280")
    .text(`${data.workspace.name} | ${data.period.label}`, 50, 102);
  doc.moveTo(50, 140).lineTo(doc.page.width - 50, 140).lineWidth(1).strokeColor("#E5E7EB").stroke();

  const cardGap = 18;
  const cardWidth = (doc.page.width - 100 - cardGap) / 2;
  const cardHeight = 92;
  const topY = 172;

  drawMetricCard({
    doc,
    x: 50,
    y: topY,
    width: cardWidth,
    height: cardHeight,
    label: "Total Income",
    value: data.summary.totalIncome,
    color: "#DCFCE7",
  });
  drawMetricCard({
    doc,
    x: 50 + cardWidth + cardGap,
    y: topY,
    width: cardWidth,
    height: cardHeight,
    label: "Total Expense",
    value: data.summary.totalExpense,
    color: "#FEE2E2",
  });
  drawMetricCard({
    doc,
    x: 50,
    y: topY + cardHeight + cardGap,
    width: cardWidth,
    height: cardHeight,
    label: "Net Profit",
    value: data.summary.netProfit,
    color: "#DBEAFE",
  });
  drawMetricCard({
    doc,
    x: 50 + cardWidth + cardGap,
    y: topY + cardHeight + cardGap,
    width: cardWidth,
    height: cardHeight,
    label: "Total GST",
    value: data.summary.totalGST,
    color: "#FFEDD5",
  });

  // Page 2 - category breakdown
  doc.addPage();
  doc.font("Helvetica-Bold").fontSize(18).fillColor("#111827").text("Category Breakdown", 50, 60);

  const categories = [...data.byCategory].sort((a, b) => b.total - a.total);
  const categoryColumns = [50, 240, 330, 400];
  let y = 100;

  doc.rect(50, y, doc.page.width - 100, 24).fill("#E5E7EB");
  doc.fillColor("#111827").font("Helvetica-Bold").fontSize(10);
  doc.text("Category", categoryColumns[0] + 8, y + 7);
  doc.text("Type", categoryColumns[1] + 8, y + 7);
  doc.text("Count", categoryColumns[2] + 8, y + 7);
  doc.text("Total Amount", categoryColumns[3] + 8, y + 7);
  y += 24;

  for (const [index, row] of categories.entries()) {
    const fill = index % 2 === 0 ? "#FFFFFF" : "#F9FAFB";
    doc.rect(50, y, doc.page.width - 100, 22).fill(fill);
    doc.fillColor("#111827").font("Helvetica").fontSize(10);
    doc.text(row.category, categoryColumns[0] + 8, y + 6, { width: 180, ellipsis: true });
    doc.text(row.type, categoryColumns[1] + 8, y + 6, { width: 80 });
    doc.text(String(row.count), categoryColumns[2] + 8, y + 6, { width: 60 });
    doc.text(formatAmount(row.total), categoryColumns[3] + 8, y + 6, { width: 120 });
    y += 22;
    if (y > doc.page.height - 60) break;
  }

  // Page 3 - top transactions
  doc.addPage();
  doc.font("Helvetica-Bold").fontSize(18).fillColor("#111827").text("Top 10 Expenses this period", 50, 60);

  const topExpenses = data.topExpenses.slice(0, 10);
  const topColumns = [50, 120, 220, 420, 490];
  y = 100;

  doc.rect(50, y, doc.page.width - 100, 24).fill("#E5E7EB");
  doc.fillColor("#111827").font("Helvetica-Bold").fontSize(10);
  doc.text("Date", topColumns[0] + 8, y + 7);
  doc.text("Category", topColumns[1] + 8, y + 7);
  doc.text("Description", topColumns[2] + 8, y + 7);
  doc.text("Amount", topColumns[3] + 8, y + 7);
  doc.text("GST Amount", topColumns[4] + 8, y + 7);
  y += 24;

  for (const [index, row] of topExpenses.entries()) {
    const fill = index % 2 === 0 ? "#FFFFFF" : "#F9FAFB";
    doc.rect(50, y, doc.page.width - 100, 24).fill(fill);
    const gstRateByCategory: Record<string, number> = {
      "Raw Materials": 18,
      Software: 18,
      Marketing: 18,
      Travel: 5,
      "Food & Entertainment": 5,
      Utilities: 18,
    };
    const gstRate = gstRateByCategory[row.category] ?? 0;
    const gstAmount = gstRate > 0 ? (row.amount * gstRate) / (100 + gstRate) : 0;

    doc.fillColor("#111827").font("Helvetica").fontSize(9.5);
    doc.text(formatDateDDMMYYYY(row.date), topColumns[0] + 8, y + 7, { width: 60 });
    doc.text(row.category, topColumns[1] + 8, y + 7, { width: 90, ellipsis: true });
    doc.text(row.description || "-", topColumns[2] + 8, y + 7, { width: 190, ellipsis: true });
    doc.text(formatAmount(row.amount), topColumns[3] + 8, y + 7, { width: 70, align: "right" });
    doc.text(formatAmount(gstAmount), topColumns[4] + 8, y + 7, { width: 52, align: "right" });
    y += 24;
  }

  const generatedAt = formatDateDDMMYYYY(new Date().toISOString());
  const range = doc.bufferedPageRange();
  for (let i = 0; i < range.count; i += 1) {
    doc.switchToPage(i);
    drawFooter({ doc, page: i + 1, totalPages: range.count, generatedAt });
  }

  doc.end();
  return pdfEnd;
}
